project_id_env: NEOFORGE_CROWDIN_PROJECT_ID
api_token_env: NEOFORGE_CROWDIN_API_TOKEN
base_path: .
base_url: 'https://neoforged.api.crowdin.com'
preserve_hierarchy: true
commit_message: '[ci skip]'
pull_request_labels:
  - l10n
files:
  - source: /loader/src/main/resources/lang/en_us.json
    translation: /loader/src/main/resources/lang/%locale_with_underscore%.%file_extension%
    dest: /fml_messages.%file_extension%
